### ISSUE TITLE
Admin color styles for this module are off

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/themeconfigurator#1]
![theme-configurator](https://cloud.githubusercontent.com/assets/3696477/26280507/343521fe-3da5-11e7-8b9a-f62c9253ea17.jpg)
@firstred

**Comment by Traumflug** [comment]
Somehow I get the impression that issues get solved, but issues don't get closed ...

Anyways:

- Colors appeared already.
- Fonts as well.
- Making the activation button white and adding a shadow around the whole thing to elevate it from the remaining page: https://github.com/thirtybees/themeconfigurator/commit/3baac0aee5ff6623d0386c0f214eff40840be303

This is how it looks now:

![grafik](https://user-images.githubusercontent.com/318581/41809887-4cbce286-76f5-11e8-9ccb-2258a887e6aa.png)

Looks good?

**Comment by Traumflug** [comment]
Looks good :-)

Please don't hesitate to open another issue if there's something left.
